layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: https://www.linkedin.com/in/pranesh-raj-1a23b997
  Phone: 8754345487
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Python
    image_url: https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg

  - name: R
    image_url: https://www.r-project.org/logo/Rlogo.png
    
  - name: SQL
    image_url: https://pngimage.net/wp-content/uploads/2018/05/database-logo-png.png
    
  - name: Tableau
    image_url: https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcS6VABkeRUpIGA5KBzUs64RlioZpBhZUswOxfljix1ids5r7Zc8&usqp=CAU
  
  - name: Power BI
    image_url: https://i.pcmag.com/imagery/reviews/02Q2JyM7Iq3t8rFTddlZMxa-7.fit_scale.size_1028x578.v_1569482292.jpg


    
 
